import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./componentsPage/Navbar";
import SplashCursor from "./components/SplashCursor/SplashCursor";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Bams Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />

        <div className="min-h-screen overflow-x-hidden bg-[#1c1c1c] md:px-20">
        <SplashCursor  />
          {children}
        </div>
      </body>
    </html>
  );
}



// app/layout.tsx
